import type { Metadata } from "next";
import "./globals.css";
import Footer from "../components/footer/footer";
import Navbar from "../components/navbar/navbar";
import { Inter } from 'next/font/google';


const inter = Inter({ 
  subsets: ["latin"],
  variable:'--font-inter'
 });

export const metadata: Metadata = {
  title: "Fire and Safety Services",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
